spring.application.name=medicalclinic
springdoc.swagger-ui.operationsSorter=method
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/compose-postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:Piotr}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update


